drop table if exists TB_EMAIL_AUTH;

/* 인증요청정보 */
CREATE TABLE TB_EMAIL_AUTH (
    EMAIL VARCHAR(100) NOT NULL COMMENT '이메일',
    AUTH_KEY VARCHAR(50) NOT NULL COMMENT '인증키',
    STATUS CHAR DEFAULT '0' COMMENT '상태 (0:인증요청, 1:인증완료)',
    AUTH_REQ_DATE TIMESTAMP NOT NULL COMMENT '인증요청일시',
    AUTH_EXPIRE_DATE TIMESTAMP NOT NULL COMMENT '요청만료일시',
    AUTH_CONFIRM_DATE TIMESTAMP COMMENT '인증일시',
    CONSTRAINT TB_EMAIL_AUTH_PK PRIMARY KEY(EMAIL, AUTH_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '이메일 인증정보';


/* 시퀀스 생성1 - 스키마 생성 */
CREATE SCHEMA EMAIL_AUTH;

/* 시퀀스 생성2 - 인증키 관련 시퀀스 */
CREATE SEQUENCE EMAIL_AUTH.AUTH_KEY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
CYCLE;
